# flags from https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/3rd-party/pytorch-install.html
services:
  pytorch:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_IMAGE: "${DOCKER_IMAGE}"
        VIDEO_GID: "${VIDEO_GID}"
        RENDER_GID: "${RENDER_GID}"
    image: ozzynet-pytorch
    pull_policy: build
    container_name: ozzynet-pytorch
    user: "${UID}:${GID}"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - "${VIDEO_GID}"
      - "${RENDER_GID}"
    ipc: host
    shm_size: 8G
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      TOKENIZERS_PARALLELISM: "false"
    volumes:
      - ./src/:/ozzynet/src
      - ./dataset/:/ozzynet/dataset
      - ./gtzan/:/ozzynet/gtzan
      - ./checkpoints/:/ozzynet/checkpoints
      - ./entrypoint.sh:/ozzynet/entrypoint.sh
      - /etc/localtime:/etc/localtime:ro
    stdin_open: true
    tty: true
    entrypoint: ./entrypoint.sh
    command: ["bash"]
