#!/bin/bash
set -e

exec env \
    HIP_VISIBLE_DEVICES="${HIP_VISIBLE_DEVICES}" \
    HSA_OVERRIDE_GFX_VERSION="${HSA_OVERRIDE_GFX_VERSION}" \
    PYTHONUNBUFFERED="${PYTHONUNBUFFERED}" \
    TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM}" \
    PATH="${PATH}" \
    HOME="/workspace" \
    "$@"
